[CmdletBinding()]param([string]$ConfigPath=(Join-Path $PSScriptRoot 'config.json'),[switch]$Once,[switch]$NonInteractive)
Set-StrictMode -Version 2.0
$ErrorActionPreference='Stop'
function New-State($Name){[pscustomobject]@{Name=$Name;Status='Unknown';Successes=0;Failures=0;ConsecutiveFailures=0;LastSuccess=$null;LastFailure=$null;LatencyMs=$null;Error=$null}}
function Update-State($State,[bool]$Success,[datetime]$At,$Latency,$ErrorText){if($Success){$State.Status='Online';$State.Successes++;$State.ConsecutiveFailures=0;$State.LastSuccess=$At;$State.Error=$null}else{$State.Status='Offline';$State.Failures++;$State.ConsecutiveFailures++;$State.LastFailure=$At;$State.Error=$ErrorText};$State.LatencyMs=$Latency;$State}
function Test-Target($Target,[int]$Timeout){$p=New-Object System.Net.NetworkInformation.Ping;try{$r=$p.Send($Target,$Timeout);[pscustomobject]@{Success=($r.Status -eq 'Success');Latency=if($r.Status -eq 'Success'){[int]$r.RoundtripTime}else{$null};Error=if($r.Status -eq 'Success'){$null}else{$r.Status.ToString()}}}catch{[pscustomobject]@{Success=$false;Latency=$null;Error=$_.Exception.Message}}finally{$p.Dispose()}}
function Safe-Text($Text){if(!$Text){return $null};($Text -replace '(?i)(token|cookie|authorization|password|secret|api[_-]?key)\s*[:=]\s*\S+','$1=[REDACTED]')}
function New-Report($Config,$Public,$Internal,$Ip){@('Local Splash Connectivity Diagnostics',"Generated: $(Get-Date -Format o)","Computer: $([Environment]::MachineName)","Public $($Config.publicTarget): $($Public.Status), $($Public.LatencyMs) ms, successes $($Public.Successes), failures $($Public.Failures)","Internal $($Config.internalTarget): $($Internal.Status), $($Internal.LatencyMs) ms, successes $($Internal.Successes), failures $($Internal.Failures)","Public IP: $Ip","Public error: $(Safe-Text $Public.Error)","Internal error: $(Safe-Text $Internal.Error)") -join [Environment]::NewLine}
function Start-Diagnostics{$c=Get-Content $ConfigPath -Raw|ConvertFrom-Json;$pub=New-State Public;$int=New-State Internal;$lastIp=$null;do{$now=Get-Date;$a=Test-Target $c.publicTarget $c.timeoutMilliseconds;Update-State $pub $a.Success $now $a.Latency $a.Error|Out-Null;$b=Test-Target $c.internalTarget $c.timeoutMilliseconds;Update-State $int $b.Success $now $b.Latency $b.Error|Out-Null;try{$ip=(Invoke-RestMethod $c.publicIpEndpoint -TimeoutSec $c.httpTimeoutSeconds).ip}catch{$ip=$lastIp};if($lastIp -and $ip -ne $lastIp){Write-Host "PUBLIC IP CHANGED: $lastIp -> $ip. Sign back into Manager if needed." -ForegroundColor Yellow};$lastIp=$ip;Write-Host "Public $($c.publicTarget): $($pub.Status) $($pub.LatencyMs)ms | Internal $($c.internalTarget): $($int.Status) $($int.LatencyMs)ms | Public IP: $ip";if($Once){break};if(!$NonInteractive -and [Console]::KeyAvailable){$k=[Console]::ReadKey($true).Key;if($k -eq 'Q'){break};if($k -eq 'C'){$report=New-Report $c $pub $int $ip;if(Get-Command Set-Clipboard -ErrorAction SilentlyContinue){Set-Clipboard $report}}};Start-Sleep $c.intervalSeconds}while($true)}
if($MyInvocation.InvocationName -ne '.'){Start-Diagnostics}
